# Site Settings
locale                   : "en-GB"
title                    : "William Fawson"
title_separator          : "-"
subtitle                 : ""
name                     : "William Fawson"
description              : "Research on reputation, morality, and prosocial behaviour."
url                      : "https://williamfawson.github.io"
baseurl                  : ""
repository               : "williamfawson/williamfawson.github.io"

# Site Author
author:
  name             : "William Fawson"
  avatar           : "profile.png"
  bio              : "Postdoctoral Research Fellow<br>London Business School"
  location         : "London, United Kingdom"
  employer         : "London Business School"
  email            : "wfawson@london.edu"

  googlescholar    : ""
  orcid            : ""
  github           : "williamfawson"
  linkedin         : "wfawson"

# Build settings

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-redirect-from

markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/

include:
  - _pages

exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
